"""Shared domain models for financial intelligence workflows."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from hashlib import sha256
from math import sqrt
from typing import Iterable
from uuid import UUID, uuid4


class EventType(str, Enum):
    """Supported financial event categories."""

    EARNINGS = "earnings"
    MACRO = "macro"
    REGULATORY = "regulatory"
    M_AND_A = "m_and_a"
    PRODUCT = "product"
    SUPPLY_CHAIN = "supply_chain"
    MARKET_MOVE = "market_move"
    RISK = "risk"
    UNKNOWN = "unknown"


class Sentiment(str, Enum):
    """Directional tone extracted from source material."""

    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"


@dataclass(frozen=True)
class RawArticle:
    """Raw immutable article captured from an upstream source."""

    source: str
    title: str
    content: str
    url: str
    published_at: datetime
    id: UUID = field(default_factory=uuid4)
    checksum: str = ""
    ingested_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self) -> None:
        if not self.checksum:
            object.__setattr__(self, "checksum", content_checksum(self.content))


@dataclass(frozen=True)
class NormalizedDocument:
    """Cleaned article ready for deduplication, extraction, and embedding."""

    raw_article_id: UUID
    source: str
    title: str
    content: str
    url: str
    published_at: datetime
    checksum: str
    duplicate_of: UUID | None = None


@dataclass(frozen=True)
class Relationship:
    """Typed graph relationship with provenance and confidence."""

    subject: str
    predicate: str
    object: str
    confidence: float
    source_document_id: UUID | None = None


@dataclass(frozen=True)
class ExtractedEvent:
    """Structured financial event extracted from a document."""

    document_id: UUID
    event_type: EventType
    entities: tuple[str, ...]
    sentiment: Sentiment
    risk_level: float
    catalysts: tuple[str, ...] = ()
    relationships: tuple[Relationship, ...] = ()
    confidence: float = 0.0
    occurred_at: datetime | None = None


@dataclass(frozen=True)
class Position:
    """Deterministic mock portfolio position."""

    ticker: str
    entry_price: float
    quantity: float
    thesis: str
    confidence: float
    sector: str = "unknown"
    id: UUID = field(default_factory=uuid4)
    opened_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def cost_basis(self) -> float:
        return self.entry_price * self.quantity


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Point-in-time portfolio analytics snapshot."""

    as_of: datetime
    market_value: float
    cost_basis: float
    unrealized_pl: float
    unrealized_pl_pct: float
    sector_exposure: dict[str, float]
    position_values: dict[str, float]
    concentration: float


@dataclass(frozen=True)
class InsightReport:
    """Autonomous insight report generated by scheduled reasoning loops."""

    cadence: str
    generated_at: datetime
    top_events: tuple[ExtractedEvent, ...]
    emerging_risks: tuple[str, ...]
    portfolio_snapshot: PortfolioSnapshot | None
    narrative: str


def content_checksum(content: str) -> str:
    """Return a stable SHA-256 checksum for exact article deduplication."""

    normalized = " ".join(content.casefold().split())
    return sha256(normalized.encode("utf-8")).hexdigest()


def cosine_similarity(left: Iterable[float], right: Iterable[float]) -> float:
    """Compute cosine similarity for semantic deduplication and retrieval."""

    left_values = list(left)
    right_values = list(right)
    if len(left_values) != len(right_values):
        raise ValueError("Vectors must have the same dimensionality.")

    dot_product = sum(a * b for a, b in zip(left_values, right_values))
    left_norm = sqrt(sum(a * a for a in left_values))
    right_norm = sqrt(sum(b * b for b in right_values))
    if left_norm == 0 or right_norm == 0:
        return 0.0
    return dot_product / (left_norm * right_norm)
