"""Shared domain contracts for the financial intelligence system."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4


class EventType(str, Enum):
    """Supported market event classes extracted from source documents."""

    EARNINGS = "earnings"
    MACRO = "macro"
    REGULATORY = "regulatory"
    MERGER = "merger"
    PRODUCT = "product"
    SUPPLY_CHAIN = "supply_chain"
    RISK = "risk"
    OTHER = "other"


class Sentiment(str, Enum):
    """Coarse sentiment labels used across extraction, graph, and reports."""

    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"


class RiskLevel(str, Enum):
    """Normalized risk labels for downstream alerting."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RelationshipType(str, Enum):
    """Graph relationship vocabulary."""

    AFFECTS = "AFFECTS"
    SUPPLIES = "SUPPLIES"
    COMPETES_WITH = "COMPETES_WITH"
    OWNS = "OWNS"
    MENTIONS = "MENTIONS"
    CORRELATED_WITH = "CORRELATED_WITH"
    EXPOSED_TO = "EXPOSED_TO"
    BENEFITS_FROM = "BENEFITS_FROM"
    HURT_BY = "HURT_BY"
    DEPENDS_ON = "DEPENDS_ON"


class LoopCadence(str, Enum):
    """Scheduled reasoning loop cadence."""

    FAST = "5m"
    MEDIUM = "1h"
    DEEP = "1d"


def utc_now() -> datetime:
    """Return a timezone-aware UTC timestamp."""

    return datetime.now(timezone.utc)


@dataclass(frozen=True)
class RawArticle:
    """Raw source article stored for auditing, replay, and retraining."""

    source: str
    title: str
    content: str
    url: str
    published_at: datetime | None = None
    id: UUID = field(default_factory=uuid4)
    checksum: str = ""
    ingested_at: datetime = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class NormalizedDocument:
    """Cleaned document emitted by parsing workers."""

    article_id: UUID
    source: str
    title: str
    content: str
    url: str
    checksum: str
    published_at: datetime | None
    ingested_at: datetime
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ExtractedEvent:
    """Structured event extracted from a normalized document."""

    document_id: UUID
    event_type: EventType
    entities: tuple[str, ...]
    sentiment: Sentiment
    risk_level: RiskLevel
    catalysts: tuple[str, ...] = ()
    macro_impact: str | None = None
    confidence: float = 0.0
    extracted_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class GraphRelationship:
    """A typed edge suitable for Neo4j persistence."""

    source: str
    target: str
    relationship: RelationshipType
    confidence: float = 1.0
    evidence_document_id: UUID | None = None
    observed_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class Position:
    """Deterministic mock portfolio position."""

    ticker: str
    entry_price: float
    quantity: float
    thesis: str
    confidence: float
    sector: str = "unknown"
    id: UUID = field(default_factory=uuid4)
    opened_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Computed portfolio metrics at a point in time."""

    market_value: float
    unrealized_pl: float
    exposure_by_sector: dict[str, float]
    win_rate: float
    position_count: int
    generated_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class InsightReport:
    """Human-readable report generated by scheduled reasoning loops."""

    cadence: LoopCadence
    title: str
    highlights: tuple[str, ...]
    risks: tuple[str, ...]
    portfolio_snapshot: PortfolioSnapshot | None = None
    generated_at: datetime = field(default_factory=utc_now)
